import type { ClassType, Instructor, Package, Session } from "@/types";
export const classes: ClassType[] = [
 {id:"foundation",slug:"foundation",name:"Foundation",shortDescription:"Learn alignment, tempo, and safe equipment transitions.",fullDescription:"A considered introduction to slow resistance work, with clear setup cues and time to understand each movement.",duration:50,intensity:"Moderate",level:"Beginner",equipment:["Specialized resistance equipment"],maximumCapacity:null,instructorIds:["maya"],image:"/images/class-foundation.jpg",accent:"clay",prerequisites:[],firstTimerSuitable:true,active:true,expect:["Equipment orientation","Controlled full-body sequences","Options for different experience levels"],preparation:["Arrive [X] minutes early","Bring water","Grip-sock requirement to be confirmed"]},
 {id:"full-body",slug:"full-body",name:"Full Body",shortDescription:"Measured strength work across the whole body.",fullDescription:"Continuous, low-impact resistance sequences designed to challenge control, stability, and endurance.",duration:50,intensity:"Challenging",level:"All levels",equipment:["Specialized resistance equipment"],maximumCapacity:null,instructorIds:["maya","nadine"],image:"/images/class-full-body.jpg",accent:"rosewood",prerequisites:["Foundation recommended for first-time clients"],firstTimerSuitable:false,active:true,expect:["Slow transitions","Sustained resistance","Instructor-led options"],preparation:["Hydrate before class","Tell your instructor privately about relevant limitations"]},
 {id:"lower-body",slug:"lower-body",name:"Lower Body",shortDescription:"Focused leg and glute strength under controlled tension.",fullDescription:"A lower-body emphasis using steady tempo and resistance. This is demonstration content pending the final class program.",duration:45,intensity:"Challenging",level:"Experienced",equipment:["Specialized resistance equipment"],maximumCapacity:null,instructorIds:["nadine"],image:"/images/class-lower.jpg",accent:"sage",prerequisites:["Prior equipment experience recommended"],firstTimerSuitable:false,active:true,expect:["Lower-body emphasis","Technical tempo cues","Short transitions"],preparation:["Choose Foundation if this is your first session"]},
 {id:"core-stability",slug:"core-stability",name:"Core + Stability",shortDescription:"Precise trunk control and integrated stability.",fullDescription:"A measured session focused on stability and whole-body coordination without medical or rehabilitation claims.",duration:45,intensity:"Moderate",level:"All levels",equipment:["Specialized resistance equipment","Mat"],maximumCapacity:null,instructorIds:["maya"],image:"/images/class-core.jpg",accent:"limestone",prerequisites:[],firstTimerSuitable:true,active:true,expect:["Stability-focused sequences","Clear alignment cues","Low-impact pacing"],preparation:["Arrive early for setup"]},
 {id:"private",slug:"private-session",name:"Private Session",shortDescription:"One-to-one instruction shaped around your experience.",fullDescription:"A private equipment session with pacing and movement selection discussed directly with an instructor.",duration:55,intensity:"Moderate",level:"All levels",equipment:["Specialized resistance equipment"],maximumCapacity:1,instructorIds:["maya","nadine"],image:"/images/class-private.jpg",accent:"espresso",prerequisites:[],firstTimerSuitable:true,active:true,expect:["Private orientation","Individual pacing","Technique feedback"],preparation:["Share relevant information privately with the studio"]}
];
export const instructors: Instructor[] = [
 {id:"maya",slug:"maya-placeholder",name:"Maya [Placeholder]",role:"Founding instructor — placeholder",shortBio:"Profile awaiting the studio’s approved biography.",fullBio:"This biography is placeholder content. Replace it with the instructor’s approved background, teaching approach, and experience.",specialties:["Foundations","Controlled strength"],credentials:["Credentials pending verification"],classIds:["foundation","full-body","core-stability","private"],portrait:"/images/instructor-maya.jpg",active:true,teachingStyle:"Precise, calm cueing — placeholder",favoriteClass:"Foundation — placeholder"},
 {id:"nadine",slug:"nadine-placeholder",name:"Nadine [Placeholder]",role:"Instructor — placeholder",shortBio:"Profile awaiting the studio’s approved biography.",fullBio:"This biography is placeholder content and makes no credential claims.",specialties:["Full-body resistance","Lower-body strength"],credentials:["Credentials pending verification"],classIds:["full-body","lower-body","private"],portrait:"/images/instructor-nadine.jpg",active:true,teachingStyle:"Focused, encouraging — placeholder",favoriteClass:"Full Body — placeholder"}
];
const d=(offset:number)=>{const x=new Date();x.setDate(x.getDate()+offset);return x.toISOString().slice(0,10)};
export const sessions: Session[] = [
 {id:"demo-1",classId:"foundation",instructorId:"maya",date:d(1),startTime:"09:00",endTime:"09:50",timeZone:"Asia/Beirut",capacity:null,bookedCount:null,status:"Available",waitlistStatus:"Not applicable",recurring:true,bookingUrl:"/book?session=demo-1",firstTimerEligible:true,demonstration:true},
 {id:"demo-2",classId:"full-body",instructorId:"nadine",date:d(1),startTime:"18:00",endTime:"18:50",timeZone:"Asia/Beirut",capacity:null,bookedCount:null,status:"Waitlist",waitlistStatus:"Open",recurring:true,bookingUrl:"/book?session=demo-2",firstTimerEligible:false,demonstration:true},
 {id:"demo-3",classId:"core-stability",instructorId:"maya",date:d(2),startTime:"10:00",endTime:"10:45",timeZone:"Asia/Beirut",capacity:null,bookedCount:null,status:"Available",waitlistStatus:"Not applicable",recurring:true,bookingUrl:"/book?session=demo-3",firstTimerEligible:true,demonstration:true},
 {id:"demo-4",classId:"lower-body",instructorId:"nadine",date:d(3),startTime:"17:30",endTime:"18:15",timeZone:"Asia/Beirut",capacity:null,bookedCount:null,status:"Cancelled",waitlistStatus:"Closed",cancellationNote:"Demonstration status",recurring:false,bookingUrl:"",firstTimerEligible:false,demonstration:true}
];
export const packages: Package[] = [
 {id:"intro",name:"First Session",description:"Introductory offer — price and inclusions to be confirmed.",type:"Intro offer",sessions:1,validity:"[Validity to confirm]",price:{USD:null,LBP:null},autoRenewal:false,freezeRules:"Not applicable",cancellationSummary:"Studio policy applies",featured:true,active:true},
 {id:"single",name:"Single Session",description:"One group session.",type:"Single class",sessions:1,validity:"[Validity to confirm]",price:{USD:null,LBP:null},autoRenewal:false,freezeRules:"Not applicable",cancellationSummary:"Studio policy applies",featured:false,active:true},
 {id:"pack",name:"Class Package",description:"Flexible session package — quantity and terms to be confirmed.",type:"Class package",sessions:null,validity:"[Validity to confirm]",price:{USD:null,LBP:null},autoRenewal:false,freezeRules:"[Rules to confirm]",cancellationSummary:"Studio policy applies",featured:false,active:true},
 {id:"membership",name:"Monthly Practice",description:"Recurring membership structure pending approval.",type:"Monthly membership",billingPeriod:"Monthly",sessions:null,validity:"[Terms to confirm]",price:{USD:null,LBP:null},autoRenewal:true,freezeRules:"[Freeze policy to confirm]",cancellationSummary:"[Cancellation terms to confirm]",featured:false,active:true},
 {id:"private-pack",name:"Private Sessions",description:"One-to-one package details to be confirmed.",type:"Private package",sessions:null,validity:"[Validity to confirm]",price:{USD:null,LBP:null},autoRenewal:false,freezeRules:"[Rules to confirm]",cancellationSummary:"Studio policy applies",featured:false,active:true}
];
export const faqs=[
 {q:"Is this suitable for a first session?",a:"Foundation and selected Core + Stability sessions are marked first-timer suitable. Final programming and eligibility are placeholders until confirmed by the studio."},
 {q:"What should I bring?",a:"Bring water and comfortable movement clothing. The grip-sock policy and arrival time are placeholders and must be confirmed."},
 {q:"Is this Pilates?",a:"The current placeholder offering combines Pilates-inspired movement with high-intensity, low-impact resistance training. Verified terminology can be enabled later in the studio configuration."},
 {q:"Can I train while pregnant or with an injury?",a:"Contact the studio privately before booking. The website does not provide medical advice; participation policies require professional review."}
];
