import type { ClassType, Instructor, Package, Session } from "@/types";

export const classes: ClassType[] = [
  {
    id: "foundation",
    slug: "foundation",
    name: "Foundation",
    shortDescription:
      "Learn alignment, tempo, and considered equipment transitions.",
    fullDescription:
      "A measured introduction to slow resistance work with clear setup cues and time to understand each movement.",
    duration: 50,
    intensity: "Moderate",
    level: "Beginner",
    equipment: ["Specialized resistance equipment"],
    maximumCapacity: 8,
    instructorIds: ["maya"],
    image: "/samples/pilates/images/class-group.webp",
    accent: "clay",
    prerequisites: [],
    firstTimerSuitable: true,
    active: true,
    expect: [
      "Equipment orientation",
      "Controlled full-body sequences",
      "Options for different experience levels",
    ],
    preparation: [
      "Arrive ten minutes early",
      "Bring water",
      "Wear grip socks for equipment sessions",
    ],
  },
  {
    id: "full-body",
    slug: "full-body",
    name: "Full Body",
    shortDescription: "Measured strength work across the whole body.",
    fullDescription:
      "Continuous, low-impact resistance sequences that challenge control, stability, and endurance.",
    duration: 50,
    intensity: "Challenging",
    level: "All levels",
    equipment: ["Specialized resistance equipment"],
    maximumCapacity: 8,
    instructorIds: ["maya", "nadine"],
    image: "/samples/pilates/images/class-group.webp",
    accent: "rosewood",
    prerequisites: ["Foundation recommended for first-time clients"],
    firstTimerSuitable: false,
    active: true,
    expect: [
      "Slow transitions",
      "Sustained resistance",
      "Instructor-led options",
    ],
    preparation: [
      "Hydrate before class",
      "Share relevant limitations privately",
    ],
  },
  {
    id: "lower-body",
    slug: "lower-body",
    name: "Lower Body",
    shortDescription:
      "Focused leg and glute strength under controlled tension.",
    fullDescription:
      "A lower-body emphasis using steady tempo, deliberate transitions, and adjustable resistance.",
    duration: 45,
    intensity: "Challenging",
    level: "Experienced",
    equipment: ["Specialized resistance equipment"],
    maximumCapacity: 8,
    instructorIds: ["nadine"],
    image: "/samples/pilates/images/class-group.webp",
    accent: "sage",
    prerequisites: ["Prior equipment experience recommended"],
    firstTimerSuitable: false,
    active: true,
    expect: [
      "Lower-body emphasis",
      "Technical tempo cues",
      "Short transitions",
    ],
    preparation: ["Choose Foundation for a first equipment session"],
  },
  {
    id: "core-stability",
    slug: "core-stability",
    name: "Core + Stability",
    shortDescription: "Precise trunk control and integrated stability.",
    fullDescription:
      "A measured session focused on stability and whole-body coordination without medical or rehabilitation claims.",
    duration: 45,
    intensity: "Moderate",
    level: "All levels",
    equipment: ["Specialized resistance equipment", "Mat"],
    maximumCapacity: 8,
    instructorIds: ["maya"],
    image: "/samples/pilates/images/class-group.webp",
    accent: "limestone",
    prerequisites: [],
    firstTimerSuitable: true,
    active: true,
    expect: [
      "Stability-focused sequences",
      "Clear alignment cues",
      "Low-impact pacing",
    ],
    preparation: ["Arrive ten minutes early for setup"],
  },
  {
    id: "private",
    slug: "private-session",
    name: "Private Session",
    shortDescription: "One-to-one instruction shaped around your experience.",
    fullDescription:
      "A private equipment session with pacing and movement selection discussed directly with an instructor.",
    duration: 55,
    intensity: "Moderate",
    level: "All levels",
    equipment: ["Specialized resistance equipment"],
    maximumCapacity: 1,
    instructorIds: ["maya", "nadine"],
    image: "/samples/pilates/images/class-group.webp",
    accent: "espresso",
    prerequisites: [],
    firstTimerSuitable: true,
    active: true,
    expect: ["Private orientation", "Individual pacing", "Technique feedback"],
    preparation: ["Share relevant information privately with the instructor"],
  },
];

export const instructors: Instructor[] = [
  {
    id: "maya",
    slug: "maya-haddad",
    name: "Maya Haddad",
    role: "Fictional concept instructor",
    shortBio:
      "A calm fictional profile used to demonstrate precise cueing and beginner guidance.",
    fullBio:
      "Maya Haddad is a fictional FORME profile created for this Spline concept. Her page demonstrates teaching approach and class relationships without claiming qualifications, employment, or real-world experience.",
    specialties: ["Foundation", "Controlled strength"],
    credentials: [],
    classIds: ["foundation", "full-body", "core-stability", "private"],
    portrait: "/samples/pilates/images/instructor-editorial.webp",
    active: true,
    teachingStyle:
      "Precise, calm cueing with time to understand each transition.",
    favoriteClass: "Foundation",
  },
  {
    id: "nadine",
    slug: "nadine-khoury",
    name: "Nadine Khoury",
    role: "Fictional concept instructor",
    shortBio:
      "A focused fictional profile used to demonstrate progressive group programming.",
    fullBio:
      "Nadine Khoury is a fictional FORME profile created for this Spline concept. Her page illustrates how a studio can communicate teaching style without publishing unverified credentials.",
    specialties: ["Full-body resistance", "Lower-body strength"],
    credentials: [],
    classIds: ["full-body", "lower-body", "private"],
    portrait: "/samples/pilates/images/instructor-editorial.webp",
    active: true,
    teachingStyle: "Focused, encouraging instruction with clear tempo cues.",
    favoriteClass: "Full Body",
  },
];

const futureDate = (offset: number) => {
  const date = new Date("2026-08-24T12:00:00+03:00");
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
};

export const sessions: Session[] = [
  {
    id: "demo-1",
    classId: "foundation",
    instructorId: "maya",
    date: futureDate(7),
    startTime: "09:00",
    endTime: "09:50",
    timeZone: "Asia/Beirut",
    capacity: 8,
    bookedCount: 3,
    status: "Available",
    waitlistStatus: "Not applicable",
    recurring: true,
    bookingUrl: "/book?session=demo-1",
    firstTimerEligible: true,
    demonstration: true,
  },
  {
    id: "demo-2",
    classId: "full-body",
    instructorId: "nadine",
    date: futureDate(7),
    startTime: "18:00",
    endTime: "18:50",
    timeZone: "Asia/Beirut",
    capacity: 8,
    bookedCount: 8,
    status: "Waitlist",
    waitlistStatus: "Open",
    recurring: true,
    bookingUrl: "/book?session=demo-2",
    firstTimerEligible: false,
    demonstration: true,
  },
  {
    id: "demo-3",
    classId: "core-stability",
    instructorId: "maya",
    date: futureDate(8),
    startTime: "10:00",
    endTime: "10:45",
    timeZone: "Asia/Beirut",
    capacity: 8,
    bookedCount: 5,
    status: "Available",
    waitlistStatus: "Not applicable",
    recurring: true,
    bookingUrl: "/book?session=demo-3",
    firstTimerEligible: true,
    demonstration: true,
  },
  {
    id: "demo-4",
    classId: "lower-body",
    instructorId: "nadine",
    date: futureDate(9),
    startTime: "17:30",
    endTime: "18:15",
    timeZone: "Asia/Beirut",
    capacity: 8,
    bookedCount: 8,
    status: "Waitlist",
    waitlistStatus: "Open",
    recurring: false,
    bookingUrl: "/contact?session=demo-4",
    firstTimerEligible: false,
    demonstration: true,
  },
];

export const packages: Package[] = [
  {
    id: "intro",
    name: "First Session",
    description:
      "One equipment orientation and a first-timer-suitable session.",
    type: "Intro offer",
    sessions: 1,
    validity: "Use within 14 days",
    price: { USD: 28, LBP: 2520000 },
    autoRenewal: false,
    freezeRules: "Not applicable",
    cancellationSummary: "12-hour demonstration cancellation window",
    featured: true,
    active: true,
  },
  {
    id: "single",
    name: "Single Session",
    description: "One group equipment session.",
    type: "Single class",
    sessions: 1,
    validity: "Use within 30 days",
    price: { USD: 35, LBP: 3150000 },
    autoRenewal: false,
    freezeRules: "Not applicable",
    cancellationSummary: "12-hour demonstration cancellation window",
    featured: false,
    active: true,
  },
  {
    id: "pack",
    name: "Five Sessions",
    description: "A flexible five-session rhythm without automatic renewal.",
    type: "Class package",
    sessions: 5,
    validity: "Use within 60 days",
    price: { USD: 145, LBP: 13050000 },
    autoRenewal: false,
    freezeRules: "Validity is fixed in this concept",
    cancellationSummary: "12-hour demonstration cancellation window",
    featured: false,
    active: true,
  },
  {
    id: "membership",
    name: "Monthly Practice",
    description: "Eight illustrative sessions in a 30-day cycle.",
    type: "Monthly membership",
    billingPeriod: "Monthly",
    sessions: 8,
    validity: "30 days",
    price: { USD: 195, LBP: 17550000 },
    autoRenewal: false,
    freezeRules: "No freeze in the demonstration",
    cancellationSummary: "No automatic renewal or charge",
    featured: false,
    active: true,
  },
  {
    id: "private-pack",
    name: "Three Private Sessions",
    description: "Three one-to-one equipment sessions.",
    type: "Private package",
    sessions: 3,
    validity: "Use within 60 days",
    price: { USD: 240, LBP: 21600000 },
    autoRenewal: false,
    freezeRules: "Validity is fixed in this concept",
    cancellationSummary: "12-hour demonstration cancellation window",
    featured: false,
    active: true,
  },
];

export const faqs = [
  {
    q: "Is this suitable for a first session?",
    a: "Foundation and selected Core + Stability sessions are marked first-timer suitable in this fictional timetable.",
  },
  {
    q: "What should I bring?",
    a: "Bring water, comfortable movement clothing, and grip socks for the illustrative equipment policy. Arrive ten minutes early.",
  },
  {
    q: "Is this Pilates?",
    a: "FORME is presented as Pilates-inspired controlled resistance training. No certification or equipment affiliation is claimed.",
  },
  {
    q: "Can I train while pregnant or with an injury?",
    a: "This concept provides no medical advice. A real studio should ask clients to contact the instructor privately and seek appropriate professional guidance.",
  },
];
